ALFMOB-44: Bag/Wish List model improvements
Mindera/Alfie-iOS pull request #12
Opened 2024-11-28 20:14 UTC by timea-v

Created a separate model for Bag and Wish List items using SKU as unique identifier instead of creating UUIDs.

2024-11-29 10:18 UTC, reisdev requested changes

2024-11-29 10:18 UTC, reisdev commented on Alfie/Alfie/Views/BagView/BagView.swift
> -                    product: product,
Just like you did for the `VerticalProductCard`, you could create a `HorizontalProductCardViewModel` for the `HorizontalProductCard`. You could also have single `ProductCardViewModel` that works for both, but there's the `VerticalProductCardConfiguration`, which may be an obstacle.

2024-11-29 10:18 UTC, reisdev commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +    }
Since this `Binding` is get-only, does it really need to be a binding? I see that, in the future, we may have the set implemented as well. It's just to clarify if it's really required.

2024-11-29 10:18 UTC, reisdev commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = SelectionProduct(
You could create a init for the`SelectionProduct` which receives the `Product` and instantiate the properties based on it.

2024-12-02 07:20 UTC, timea-v commented on Alfie/Alfie/Views/BagView/BagView.swift
> -                    product: product,
I added view model, there are some more differences so I created a separate one: [87931e3](https://github.com/Mindera/Alfie-iOS/pull/12/commits/87931e3da5d34fb69f421df4259043c3d8139b6e)

2024-12-02 07:25 UTC, timea-v commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = SelectionProduct(
I updated it: [87931e3](https://github.com/Mindera/Alfie-iOS/pull/12/commits/87931e3da5d34fb69f421df4259043c3d8139b6e)

2024-12-02 07:25 UTC, timea-v commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +    }
You are right, I overcomplicated it because there was an action handler for on Product Card. I changed it: [87931e3](https://github.com/Mindera/Alfie-iOS/pull/12/commits/87931e3da5d34fb69f421df4259043c3d8139b6e)

2024-12-04 11:45 UTC, reisdev approved these changes

2024-12-09 14:00 UTC, p4checo approved these changes

2024-12-09 19:17 UTC, timea-v commented on Alfie/Packages/Models/Sources/Features/ProductListingViewModelProtocol.swift
> +    func isFavoriteState(for product: Product) -> Binding<Bool>
I agree, that was my first approach, I am not sure why I introduce `Binding` in addition to handling the state through API. I changed it here: [4d55b6ce](https://github.com/Mindera/Alfie-iOS/pull/12/commits/4d55b6cea5dfc23ef21519fe47589cf4fb6eb9ab)

2024-12-09 19:17 UTC, timea-v commented on Alfie/Packages/Models/Sources/UI/ProductCard/HorizontalProductCardViewModel.swift
> +    public var designer: String = ""
I addressed it here: [ec05332](https://github.com/Mindera/Alfie-iOS/pull/12/commits/ec053324347e752b95b244bd4d3157a9694f48fd)

2024-12-09 19:17 UTC, timea-v commented on Alfie/Packages/Models/Sources/UI/ProductCard/VerticalProductCardViewModel.swift
> +    public var colorTitle: String = ""
I addressed it here: [ec05332](https://github.com/Mindera/Alfie-iOS/pull/12/commits/ec053324347e752b95b244bd4d3157a9694f48fd)

2024-12-10 10:31 UTC, p4checo commented
🚀

2024-12-10 12:12 UTC, merged