ALFMOB-49: Wishlist feature adjustments
Mindera/Alfie-iOS pull request #14
Opened 2024-12-05 19:46 UTC by timea-v

Implemented Wishlist feature for the following scenarios:
- Shop, Bag screen right toolbar icon
- Account list item
- Changed display of wishlist in tab bar in real time (without needing to restart the app)

https://github.com/user-attachments/assets/3c26e8cb-88be-409e-8a45-3b973fa6438b

2024-12-09 14:11 UTC, p4checo requested changes

2024-12-09 14:11 UTC, p4checo commented on Alfie/Alfie/Modifiers/DefaultToolbarModifier.swift
> +    public init(screen: Screen, viewModel: DefaultToolbarModifierViewModelProtocol) {
It's a bit strange to pass a VM into a modifier... 🤔  Wouldn't injecting a `isWishlistEnabled: Bool` parameter/property be enough? Or maybe even use the Coordinator since we already use to see if the Debug Menu is being presented?

This seems to have added significant complexity (more protocols, more conformances, more mocks) without much benefit.

2024-12-10 19:24 UTC, p4checo approved these changes
🚀

2024-12-11 16:01 UTC, timea-v commented on Alfie/Alfie/Modifiers/DefaultToolbarModifier.swift
> +    public init(screen: Screen, viewModel: DefaultToolbarModifierViewModelProtocol) {
I refactored it and injected the value on `Coordinatior`.  Please check my latest commits.

2024-12-12 05:12 UTC, naveenmindera approved these changes

2024-12-16 12:58 UTC, merged