[ALFMOB-47] Add order-by to "Product Listing" screen
Mindera/Alfie-iOS pull request #15
Opened 2024-12-18 18:47 UTC by reisdev

## Description

This PR adds the order-by functionality to the product listing screen, along with the `Filter` screen.

## Evidence

https://github.com/user-attachments/assets/bd89c12b-a7dd-4339-82b6-9a77daa55537

2024-12-23 14:16 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/API/Navigation/NavigationService.swift
> +        try await bffClient.getHeaderNav(handle: screen.handle, includeSubItems: false, includeMedia: false)
Do we need this change? Even for demo purposes it might be good to have subcategories I guess.

2024-12-23 14:18 UTC, timea-v requested changes
Besides documentation changes, only minor observations

2024-12-26 12:09 UTC, reisdev commented on Alfie/Packages/Core/Sources/GraphQL/Schema/schema-products.graphqls
> +DJ often display a price range or a 'from'.
Fixed on c994d00

2024-12-26 12:10 UTC, reisdev commented on Alfie/Packages/Core/Sources/GraphQL/Schema/schema-products.graphqls
> +  "DJ refer to products (including variants) as style numbers, so this is DJ's unique identifier."
Fixed on c994d00

2024-12-26 12:12 UTC, reisdev commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +        }
Rolled back on a83ced5

2024-12-26 12:13 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/BFFService/Converters/Colour+Converter.swift
Improved on 743b719

2024-12-26 12:13 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/BFFService/Converters/SizeTree+Converter.swift
Improved on 743b719

2024-12-26 12:13 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/BFFService/Converters/Variant+Converter.swift
Improved on 743b719

2024-12-26 12:14 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/API/Navigation/NavigationService.swift
> +        try await bffClient.getHeaderNav(handle: screen.handle, includeSubItems: false, includeMedia: false)
You're right. I forgot to undo this. Reverted on 0ef7972

2024-12-30 14:07 UTC, timea-v commented on .slather.yml
>  binary_basename: DavidJones
```suggestion
binary_basename: Alfie
```

2024-12-30 18:34 UTC, timea-v approved these changes

2025-01-06 17:19 UTC, p4checo approved these changes
Nice addition and clean ups. Only a couple of minor comments 😉

2025-01-06 17:19 UTC, p4checo commented on Alfie/Alfie/Views/HomeView/HomeView.swift
> +            ThemedButton(text: isUserLogged ? "Sign out" : "Sign in") {
Shouldn't we use localization for this?

2025-01-06 17:19 UTC, p4checo commented on Alfie/Alfie/Views/ProductListing/Components/ProductListingInfoFilterBar.swift
> +        filterAction: @escaping () -> Void) {
closing `) {` should be on the next line 💅🏼

2025-01-06 17:19 UTC, p4checo commented on Alfie/Packages/StyleGuide/Sources/Components/SortBy/SortByType.swift
> +    case priceHighToLow = "HIGH_TO_LOW"
for consistency, perhaps `priceDesc` and `priceAsc`?

2025-01-07 13:04 UTC, reisdev commented on Alfie/Alfie/Views/ProductListing/Components/ProductListingInfoFilterBar.swift
> +        filterAction: @escaping () -> Void) {
Fixed in [ce4f7c6](https://github.com/Mindera/Alfie-iOS/pull/15/commits/ce4f7c624553f27349f5393a71b686e71f2ef559)

2025-01-07 13:04 UTC, reisdev commented on Alfie/Alfie/Views/HomeView/HomeView.swift
> +            ThemedButton(text: isUserLogged ? "Sign out" : "Sign in") {
Of course.

Done in [ce4f7c6](https://github.com/Mindera/Alfie-iOS/pull/15/commits/ce4f7c624553f27349f5393a71b686e71f2ef559)

2025-01-07 20:33 UTC, merged