ALFMOB-22: Add size picker to PDP
Mindera/Alfie-iOS pull request #3
Opened 2024-10-31 18:30 UTC by timea-v

Size selection UI was missing. The PR integrates existing size selector UI components in PDP. 
Includes some code improvements for reusability and testability.

2024-11-06 18:09 UTC, p4checo requested changes
nice work, some pending questions 🤓

2024-11-06 18:09 UTC, p4checo commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSwatch.swift
> +    public init(id: String = UUID().uuidString, name: String, state: ItemState) {
why do we pass a random value by default? Don't we get an `id` from the API?
If we don't receive an `id`, can't the name be used as the identifier? 🤔

2024-11-06 18:09 UTC, p4checo commented on Alfie/Packages/StyleGuide/Sources/Demo/ColorBanner/ColorBannerDemoView.swift
> +                        configuration: ColorSelectorConfiguration(selectedTitle: Self.selectedTitle, items: Self.items),
Any reason why you converted `.init` to their explicit variant? (multiple cases) 💅🏼

2024-11-06 18:09 UTC, p4checo commented on Alfie/Packages/StyleGuide/Sources/Theme/Components/SizingBanner/ColorAndSizingSelectorHeaderView.swift
> +            Button(action: {
`action` should be on the next line? (and `label` as well)

2024-11-07 14:42 UTC, timea-v commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSelectorConfiguration.swift
> +    @Published public var selectedItem: SizingSwatch?
I am not sure, because initial value of `selectedItem` is mapped from API and then can be changed by user interaction.

2024-11-08 13:59 UTC, timea-v commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSwatch.swift
> +    public init(id: String = UUID().uuidString, name: String, state: ItemState) {
I removed it here: [1e91d3c](https://github.com/Mindera/Alfie-iOS/pull/3/commits/1e91d3ca91b4c9f57e8166584d7e681d68fa036f)

2024-11-08 14:01 UTC, timea-v commented on Alfie/Packages/StyleGuide/Sources/Theme/Components/SizingBanner/ColorAndSizingSelectorHeaderView.swift
> +            Button(action: {
I fixed it here: [41a0669](https://github.com/Mindera/Alfie-iOS/pull/3/commits/41a0669de21d95430ee8e7662ab4828099817af4)

2024-11-08 14:02 UTC, timea-v commented on Alfie/Packages/StyleGuide/Sources/Demo/ColorBanner/ColorBannerDemoView.swift
> +                        configuration: ColorSelectorConfiguration(selectedTitle: Self.selectedTitle, items: Self.items),
I've reset the changes

2024-11-11 17:58 UTC, p4checo requested changes
Definitely improved! Still think we can iron out some edges 🤓

2024-11-11 17:58 UTC, p4checo commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsView.swift
> +                    .init(id: UUID().uuidString, name: "", type: .url(URL.fromString("https://www.alfieproj.com/productimages/thumb/3/2479864_22579704_13941430.jpg"))),
we don't need to generate UUIDs for the IDs to be unique, why not `"1"`, `"2"`, ...?

(multiple cases)

2024-11-11 17:58 UTC, p4checo commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSwatch.swift
>      public let id: String
if the `name` is unique (as it probably should), then we can define `var id: String { name }` 💅🏼

2024-11-11 17:58 UTC, p4checo commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsView.swift
> +        guard !viewModel.sizingSelectionConfiguration.items.isEmpty else { return true }
shouldn't we return `false` on the `else` clause? 🤔

2024-11-11 17:58 UTC, p4checo commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsView.swift
> +        let productStockCount = viewModel.sizingSelectionConfiguration.items.reduce(0) {
we can use `reduce(into:)` to avoid intermediate copies, which uses an `inout` parameter (i.e. use with `+=`)

2024-11-11 17:59 UTC, p4checo commented on Alfie/Packages/Models/Sources/UI/ColorSizingSelectorConfigurationProtocol.swift
> +public protocol ColorSizingSelectorConfigurationProtocol: ObservableObject {
As discussed, I think we can have a single generic class `ColorAndSizingSelectorConfiguration<Swatch: ColorAndSizingSwatchProtocol>: ObservableObject` that abstract the swatch type.

2024-11-11 18:00 UTC, p4checo commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSelectorConfiguration.swift
> +    @Published public var selectedItem: SizingSwatch?
As discussed, gave it a go and it complicates things a bit in `ProductDetailsViewModel` because we're using these Configuration types to store state and observe changes on the picker components. Lets leave it as is for now.

2024-11-11 18:42 UTC, timea-v commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsView.swift
> +        guard !viewModel.sizingSelectionConfiguration.items.isEmpty else { return true }
If it is empty we need to show "One Size", this is the logic on Android implementation.

2024-11-11 18:45 UTC, p4checo approved these changes
Looking good! Feel free to resolve my other conversations and move on. Thanks! 🚀

2024-11-11 18:46 UTC, p4checo commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSwatch.swift
>      public let id: String
On the other side, if the IDs come from the API (not sure why), we should probably keep them

2024-11-11 18:48 UTC, timea-v commented on Alfie/Packages/Models/Sources/UI/SizeSelection/SizingSwatch.swift
>      public let id: String
`ProductSize` and `Colour` have `id` on API and it is mapped to `SizingSwatch` and `ColorSwatch` in `ProductDetailsViewModel`

2024-11-11 18:58 UTC, timea-v commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsView.swift
> +        let productStockCount = viewModel.sizingSelectionConfiguration.items.reduce(0) {
Changed it here: [770c107](https://github.com/Mindera/Alfie-iOS/pull/3/commits/770c1075ad2341a8859ac8927f10548033c71721)

2024-11-13 13:21 UTC, merged