ALFMOB-40: Implement mock Add to bag and Add to wish list functionality
Mindera/Alfie-iOS pull request #5
Opened 2024-11-13 17:46 UTC by timea-v

We currently don't have API implementation for Add to bag and Add to wish list, this PR mocks this functionality for a better presentability of app user flows.

https://github.com/user-attachments/assets/7d6c6bc1-49f4-4e3a-aeba-335038f66bd0

2024-11-19 10:04 UTC, reisdev approved these changes

2024-11-19 12:50 UTC, timea-v commented on Alfie/Alfie/Views/WishListView/WishListView.swift
> +                        switch type {
Yes, I addressed it: [3f9b4f6](https://github.com/Mindera/Alfie-iOS/pull/5/commits/3f9b4f6a9233d2a1df4f399d804adf1db68a33df)

2024-11-20 10:39 UTC, p4checo requested changes
Nice addition, but I think we should improve the approach a bit 😇

2024-11-20 10:39 UTC, p4checo commented on Alfie/Alfie/Views/BagView/BagView.swift
> +    @EnvironmentObject var mockContent: MockContent
I don't think we should be mocking content at the View level, but instead at the Model layer (which then feed the VMs). Multiple cases throughout

In this particular screen, If we don't have a Bag API yet, then we can assume it will be a list and not a webview, so that we can show the mocked data.

2024-11-20 10:39 UTC, p4checo commented on Alfie/Alfie/Views/ProductListing/ProductListingView.swift
> +            mockContent.wishlistProducts.append(product)
business logic like this should not live on the View. Since we are mocking remote data, this should probably be done on some mocked client or service which would contain and manage this mocked state locally.

2024-11-20 10:39 UTC, p4checo commented on Alfie/Packages/StyleGuide/Sources/Components/ProductCards/VerticalProductCard.swift
> +        colorTitle: String = "",
maybe this view needs a VM? I'm counting 16 parameters now, one of which is already a configuration object 😅

2024-11-22 12:03 UTC, p4checo commented on Alfie/Alfie/Views/WishListView/WishListView.swift
> +    #if DEBUG
same as before, the view should have a constant implementation

2024-11-22 17:40 UTC, timea-v commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsViewModel.swift
> +        guard
In style guide it states to put each condition on new line:

<img width="837" alt="Screenshot 2024-11-22 at 19 38 42" src="https://github.com/user-attachments/assets/4f255c7f-b0f9-4b64-b30e-14bcde9453d4">

2024-11-22 18:10 UTC, timea-v commented on Alfie/Alfie/Views/BagView/BagView.swift
> +    #if DEBUG
I was not sure how the future API will be implemented, but I agree that we could change it if necessary in the future. Removed it: [4b87774](https://github.com/Mindera/Alfie-iOS/pull/5/commits/4b87774e67337533f2c3b717b67c3e3b18418fb9)

2024-11-22 18:12 UTC, timea-v commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = Product(
We need to have unique item for different color and size for the same product in bag/wishlist. I updated the Product initialization not to have default id value: [4b87774](https://github.com/Mindera/Alfie-iOS/pull/5/commits/4b87774e67337533f2c3b717b67c3e3b18418fb9)

2024-11-22 18:12 UTC, timea-v commented on Alfie/Alfie/Views/WishListView/WishListView.swift
> +    #if DEBUG
Removed it: [4b87774](https://github.com/Mindera/Alfie-iOS/pull/5/commits/4b87774e67337533f2c3b717b67c3e3b18418fb9)

2024-11-22 18:20 UTC, timea-v commented on Alfie/Packages/Mocks/Sources/Core/Features/MockBagDependencyContainer.swift
>  public class MockBagDependencyContainer: BagDependencyContainerProtocol {
Good catch, I created a ticket for it: https://mindera.atlassian.net/jira/software/projects/ALFMOB/boards/289?selectedIssue=ALFMOB-41

2024-11-22 19:18 UTC, timea-v commented on Alfie/Packages/StyleGuide/Sources/Components/ProductCards/VerticalProductCard.swift
> +        colorTitle: String = "",
I added one: [d6fe68e](https://github.com/Mindera/Alfie-iOS/pull/5/commits/d6fe68eb07884e5e583828f53cc3d5d2e6740e92)

2024-11-22 19:37 UTC, timea-v commented on Alfie/Alfie/Views/BagView/BagView.swift
> +    @EnvironmentObject var mockContent: MockContent
I refactored the mocking to use mock services instead.

2024-11-26 13:11 UTC, p4checo approved these changes

2024-11-26 13:11 UTC, p4checo commented on Alfie/Alfie/Views/ProductDetails/ProductDetailsViewModel.swift
> +        guard
I stand corrected! Thanks for pointing it out 🙏🏼

2024-11-26 13:11 UTC, p4checo commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = Product(
I'm not following why that's necessary. If what identifies each product in the bag/wishlist is not the `id` but the combination of id + color + size, then that should be the id, not a randomly generated one 😅

2024-11-26 13:40 UTC, timea-v commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = Product(
I guess this can change in the future, like we won't want to have separate item in wishlist for each size/colour, and we might have a separate model object, not `Product`. Since this was only mocking and there are some open points about the feature I thought it is best to reuse the `Product`. What do you think?

2024-11-26 15:07 UTC, p4checo commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = Product(
yes, I think we need to have a separate model on Wishlist/Bag if we need to differentiate between product variants

2024-11-26 18:04 UTC, timea-v commented on Alfie/Alfie/Views/ProductListing/ProductListingViewModel.swift
> +            let selectedProduct = Product(
I can do that, at least to organize mock logic better even if the requirements will not be the same as the current code. Ticket created: https://mindera.atlassian.net/browse/ALFMOB-44

2024-11-26 18:13 UTC, merged