Alfmob 33 implemented ci cd
Mindera/Alfie-iOS pull request #7
Opened 2024-11-22 07:26 UTC by naveenmindera

2024-11-22 10:38 UTC, p4checo requested changes
Nice one! Still some pending questions though 🤓

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +      - ALFMOB-33_Implemented_CI_CD
I don't think we should keep this, right? 😄

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +    - cron: '0 23 * * 0' # Every Sunday at 23:00 GMT
do we really need this, if we build for every merge to `main`? 🤔

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +      - name: Run Static Code Analysis
this is not static code analysis, it's linting, right?

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +          'platform=iOS Simulator,name=iPhone 14'
the destination should probably be an env var, so we can change it easily as needed

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +        run: agvtool next-version -all
where is the new build number stored? If this always increments from what's on the project then it will always generate the same BN, right?

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +          xcode-version: 16
The [`macos-latest`](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode)(`macos-14-arm64`) image we're using doesn't appear to have Xcode 16 in it, but the [`macos-14`](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode) (non arm) does, which is odd.

Anyway, I think we can pick the Xcode version by setting an env variable instead of using an action, e.g.
`DEVELOPER_DIR: '/Applications/Xcode_16.1.app/Contents/Developer'`

2024-11-22 10:38 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +        run: echo "Scheduled Debug Build for TestFlight"
this seems to be incomplete, yes?

2024-11-22 11:03 UTC, reisdev commented on Alfie/.github/workflows/alfie.yml
> +          xcode-version: 16
We could also use `xcodes` cli and a `.xcode-version` file, and leverage brew to do this setup.

2024-11-22 11:04 UTC, reisdev commented on Alfie/Alfie.xcodeproj/project.pbxproj
> +		};
There's no need to add the `.github` folder to the `.xcodeproj`, neither the `alfie.yml` file

2024-11-22 17:13 UTC, naveenmindera commented on Alfie/.github/workflows/alfie.yml
> +        run: agvtool next-version -all
What I read about agvtool is, it increases the "CURRENT_PROJECT_VERSION" in project file, so the build number stores in CURRENT_PROJECT_VERSION. But I have to test this, once the workflow is ready.

2024-11-26 15:17 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +          xcode-version: 16
why add even more tooling/setup when a good old env var is enough? 😅

2024-11-26 15:17 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +        run: agvtool next-version -all
Ok, maybe the question should be: How will build numbers be **managed**?, i.e:
1. when are they incremented, and by who?
3. how are they stored/persisted across builds?

2024-11-26 15:17 UTC, p4checo commented on Alfie/Alfie.xcodeproj/project.pbxproj
> +		};
I think the idea is that we can edit these files while working on the project in Xcode, instead of having to open another editor. 

To your point, I think we might not need to add the whole folder and just add the relevant files.

IMO we just need to be careful that these files aren't added to the app target, but I don't see any problem in adding them to the project as references. In other projects I've worked on we even create a group _without folder_, and add file references to it for all these CI/tooling/setup/documentation files

2024-11-29 05:56 UTC, naveenmindera commented on Alfie/.github/workflows/alfie.yml
> +        run: agvtool next-version -all
Build numbers are incremented by the pipeline whenever a new build is triggered, but this build number will exist temporarily in the pipeline. Now it makes sense, we need to commit back the version number to the repo, to maintain the update version across builds

2024-12-02 15:10 UTC, p4checo requested changes
We're on the right path, but still some rough edges here and there 😄

2024-12-02 15:10 UTC, p4checo commented on Alfie/fastlane/Appfile
> +apple_id("naveen.katari@mindera.com") # Your Apple Developer Portal username
I don't think this is correct or needed. If we use API Key auth we don't need an Apple ID

2024-12-02 15:10 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +         fastlane pilot upload -i $PWD/build/App.ipa
we're not using the `beta` lane anywhere, or am I missing something? 🤔

2024-12-17 17:36 UTC, p4checo requested changes
nice additions! We're on the right path 😉

2024-12-17 17:36 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    sh("xcodebuild test -scheme Alfie -destination '#{ENV['IOS_DESTINATION']}'")
perhaps use `run_tests` action (aka `scan`) ?

https://docs.fastlane.tools/getting-started/ios/running-tests/

We can also set `SCAN_DESTINATION` and any other env var once which then gets passed automatically to each fastlane action. Take a look [here](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb) for scan's parameters, for instance.

2024-12-17 17:36 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    sh("swiftlint") # Runs SwiftLint
there's a [swiftlint](https://docs.fastlane.tools/actions/swiftlint/) fastlane action. I have mixed feelings about bundling `swiftlint` executable in the project, but I tend to prefer it being povided externally (e.g. via brew, SPM plugin, ...)

2024-12-17 17:36 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    api_key = app_store_connect_api_key(
I don't think we need to store the `api_key`, as this action stores it on the environment for subsequent actions to use (such as `upload_to_testflight`, `match`, etc)

2024-12-17 17:36 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    increment_build_number
we are incrementing the build number, but how is it updated after each build?

Shouldn't we get the last tag's value, extract the BN,  then increment and set it on the Xcode project instead?

2024-12-17 17:36 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    version = get_version_number(xcodeproj: "Alfie.xcodeproj")
we can and probably should store the Xcode project's path on an env var, which avoids duplication and possible errors.

2024-12-17 17:36 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +        run: agvtool next-version -all
Continuing discussion on the new changes

2025-01-29 16:35 UTC, JoaoPinhoMinder commented on Alfie/fastlane/Fastfile
> +    sh("swiftlint") # Runs SwiftLint
Like we talked, added `swiftlint` and `xcbeautify` in a `Brewfile` here: [ALFMOB-33: Add environment variables file and Brewfile](https://github.com/Mindera/Alfie-iOS/pull/7/commits/4f56e0dd393fe559bbf048aa4dad8abbbd2ef8ec)

2025-01-31 11:38 UTC, JoaoPinhoMinder commented on Alfie/fastlane/Fastfile
> +    increment_build_number
Updated like we talked on [ALFMOB-33: Adjust environment variables and update script](https://github.com/Mindera/Alfie-iOS/pull/7/commits/1d03213baae363ab449aaa560cc794e13a269ab3)

2025-01-31 11:39 UTC, JoaoPinhoMinder commented on Alfie/fastlane/Fastfile
> +    version = get_version_number(xcodeproj: "Alfie.xcodeproj")
Project version isn't updated anymore like we talked. JFY, now we only update build number and tag it, app version is manually managed for now: [ALFMOB-33: Adjust environment variables and update script](https://github.com/Mindera/Alfie-iOS/pull/7/commits/1d03213baae363ab449aaa560cc794e13a269ab3)

2025-02-11 15:43 UTC, JoaoPinhoMinder commented
The original requirements have change a little, so will ask for a full review of this pull request.

2025-02-12 19:21 UTC, p4checo requested changes
Great work! 💪🏼 
Still some things that need improvement and cleaning up 😉

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +# This file contains the fastlane.tools configuration
I think we can remove this header comment boilerplate

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +  lane :validate_tests do
as mentioned previously, perhaps `test` does the trick (And "Run Tests" as description). To avoid collisions with `run_tests`, we can also use the actions' original names, `scan` instead of `run_tests`, `gym` instead of `build_app`, etc

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +  desc "Deploy to TestFlight using Git tags"
Perhaps "Build and deploy app release to TestFlight"?

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +  lane :beta do
we're not calling it Beta, so perhaps just `release` does the trick

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    sh("git config user.name '#{ENV['GIT_USER_NAME']}'")
to make our logs a bit less verbose, perhaps we could bundle these shell commands into just two (e.g. with `;` between commands). One to set user name and email, and another to set the tag and push 💅🏼

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +    UI.message("🔢 Last Build Number: #{last_build_number}")
we could merge these 2 log messages into a single one, like: `🔢 New Build Number: #{last_build_number} -> #{new_build_number}")`

The `increment_build_number` also logs the BN that it sets I think.

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +      scheme: ENV['SCHEME'],
this can be set via `GYM_SCHEME` in `.env.default`, similar for the other parameters.

Please check: https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/options.rb

2025-02-12 19:21 UTC, p4checo commented on Alfie/Brewfile
> +brew "xcbeautify"
please add a newline at the end of each file (multiple cases)

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/.env.default
> +BUILDLOGS_PATH=${ARTIFACTS_PATH}
`ARTIFACTS_PATH` is not being defined

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/.env.default
> +BUILD_CONFIGURATION="Release"
This should only be set to `Release` for release builds

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/.env.default
> +GYM_CLONED_SOURCE_PACKAGES_PATH=${SPM_CLONED_DEPENDENCIES_PATH}
`SPM_CLONED_DEPENDENCIES_PATH` is not being defined anywhere. We typically use this to control where SPM  dependencies are cloned so that we can cache them and/or access any binaries within them (e.g. Crashlytics symbol upload script)

That reminds me that we should migrate Crashlytics symbol upload to be made only in CI release builds, not on every build via a build phase (as it is now) 😅

2025-02-12 19:21 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +          name: iOS-Test-Results
perhaps `Test artifacts`?

2025-02-12 19:21 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +  branch-validation:
not a big fan of this name, perhaps `test`? (Don't forget to update the `needs:` clause in the release job)

2025-02-12 19:21 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +  testflight-build:
perhaps `release`?

2025-02-12 19:21 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +      - name: Deploy to TestFlight
"Build and deploy release to TestFlight" 💅🏼

2025-02-12 19:21 UTC, p4checo commented on Alfie/fastlane/Fastfile
> +  # Helper lane to renew Code Signing certificates/provisioning profiles
as detailed on the code signing document,  please add a `mock-ci-env.sh` script in a `scripts` folder so it's easier to mock the CI environment locally in the future. Be careful not to commit any sensitive data though 😆

2025-02-14 17:32 UTC, p4checo requested changes
looking good! We're almost there 😉

2025-02-14 17:32 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +  ARTIFACTS_PATH: "~/Library/Developer/Xcode/DerivedData/Logs/Test"
we don't need to store it on the DerivedData folder, something like `/tmp/alfie-artifacts` also works fine 💅🏼

2025-02-14 17:32 UTC, p4checo commented on Alfie/Gemfile
> +gem "fastlane"
that's running locally, right? 😆 I assume that you're invoking it as `bundle exec fastlane <lane>` locally which uses bundler, however in CI we're just invoking `fastlane <lane>`

Nonetheless, I think that we should probably add a step to install Homebrew formulas and another to install Ruby dependencies, so in case the GH image stops having these tools our CI will keep working. It also prepares the setup in case we add any Homebrew/Ruby dependency that's not bundled in the GH image by default.

2025-02-14 17:32 UTC, p4checo commented on Alfie/Brewfile
> +brew "xcbeautify"
You're right. Missed that 🙈 

However, we don't typically manage/install dependencies from fastlane, but rather as part of CI (as in steps). Please see my other comment regarding Homebrew dependencies 😉

2025-02-18 13:12 UTC, p4checo requested changes
small fixes

2025-02-18 13:12 UTC, p4checo commented on Alfie/.github/workflows/alfie.yml
> +  SPM_CLONED_DEPENDENCIES_PATH: "tmp/SourcePackages"
as discussed, please use `/tmp/foo` and not `tmp/foo` as the first is an absolute path (on the machine's root) and the second is a relative path (to the project folder)

2025-02-19 10:31 UTC, p4checo approved these changes
🚀

2025-02-19 10:34 UTC, reisdev approved these changes

2025-02-19 10:39 UTC, merged