[ALFMOB-24] Feature Toggle on debug menu
Mindera/Alfie-iOS pull request #8
Opened 2024-11-22 10:01 UTC by reisdev

## Changelog

* Create `FeatureToggle` screen
* Change `LocalConfigurationProvider` to use `UserDefaults` instead of a json file
* Add wildcard to `.gitignore` to avoid adding every new SPM package

## Evidence

![Simulator Screenshot - iPhone 16 Pro - 2024-11-22 at 10 00 29](https://github.com/user-attachments/assets/8775036f-65ce-449f-99a6-3eb5a6364c32)

![Video demo](https://github.com/user-attachments/assets/342df50e-f845-4513-b49b-3c3fdb563b2d)

2024-11-22 11:16 UTC, p4checo requested changes
Nice work! Some suggestions and a bit of clean up missing 😄

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleView.swift
> +		LazyVGrid(columns: [GridItem()]) {
why a `LazyVGrid` and not a `LazyVStack`? 🤔

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleView.swift
> +			ForEach(viewModel.features.sorted { $0.key > $1.key }, id: \.key) { feature, isEnabled in
this business logic should be on the VM

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +	init(service: some ConfigurationServiceProtocol) {
why do we need `some` here? 🤔 

also, shouldn't this receive the provider it's attached to, instead of the whole service?

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +		guard
if the `guard` fits a single line, we don't need to break it

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +	@Published private(set) var features: [String: Bool] = [:]
couldn't we use `[ConfigurationKey: Bool]` instead?

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +		let identifier = feature.capitalized.replacingOccurrences(of: "_", with: "")
perhaps using the config key's raw value is better and less error prone? Also not sure about having to use `Key<>Feature`

2024-11-22 11:16 UTC, p4checo commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +        guard
no need to break this `guard` if it fits 120 chars (multiple cases)

2024-11-22 11:16 UTC, p4checo commented on Alfie/Packages/Models/Sources/Services/Configuration/ConfigurationProviderProtocol.swift
> +	func set(_ value: Bool, for key: ConfigurationKey)
we should not change the `ConfigurationProviderProtocol` API to allow writing configs. This should be a capability of a single provider

2024-11-22 11:16 UTC, p4checo commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +	public func updateFeature(_ key: ConfigurationKey, isEnabled: Bool) {
the `ConfigurationService` should be read only

2024-11-22 11:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +	func description(for feature: String) -> LocalizedStringResource {
if we use `ConfigurationKey` then we can add a computed property for the localized text

2024-11-22 11:31 UTC, reisdev commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleView.swift
> +		LazyVGrid(columns: [GridItem()]) {
I have the same question? 😅

Consider it fixed.

2024-11-22 11:33 UTC, reisdev commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +		let identifier = feature.capitalized.replacingOccurrences(of: "_", with: "")
I decided to pre-process it because, otherwise, we'll have localisation keys like `Keyios_wishlistFeature`, which seemed out-of-place.

2024-11-22 11:33 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +        guard
Ok

2024-11-22 11:35 UTC, reisdev commented on Alfie/Packages/Models/Sources/Services/Configuration/ConfigurationProviderProtocol.swift
> +	func set(_ value: Bool, for key: ConfigurationKey)
Ok, I'll undo it.

2024-11-22 12:05 UTC, reisdev commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
Ok, I can get it to work this way. The only problem that I see is:

> How to bypass all the providers and use only the `DebugConfigurationProvider`?

Any ideas?

2024-11-22 12:16 UTC, p4checo commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
if the `DebugConfigurationProvider` is the first of the chain, then if it returns a value (and not `nil`) it will prevail over all other providers. That's how the pattern being used (chain of responsibility) works.

2024-11-22 12:16 UTC, p4checo commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +		let identifier = feature.capitalized.replacingOccurrences(of: "_", with: "")
Not related to your changes, but I never understood the `KeyFooBar` approach. Personally I always used sort of reverse domain notation with snake_case, and I think it's better for most cases and this is no exception 😅 

So I would see this as `feature_toggle.<feature_toggle_name>`, or even the `<feature_toggle_name>` directly. However, to not go against the current localization _status quo_, perhaps we can leave it as is.

2024-11-22 12:20 UTC, reisdev commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
So the toggle for a "global override" would force the provider to return `nil` when it's not enabled, right?

2024-11-22 12:23 UTC, p4checo commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
Precisely

2024-11-22 12:53 UTC, timea-v commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
Wouldn't this approach cause too many user interaction to get to a single feature? Maybe we could just have set remote toggle by default in debug menu for all features and only if that changes to on/off we set the debug config value in `DebugConfigurationProvider`, otherwise it would be `nil`?

2024-11-22 13:54 UTC, reisdev commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +		let identifier = feature.capitalized.replacingOccurrences(of: "_", with: "")
I agree with you and prefer the same pattern, but using camel-case. I've just followed the current localisation keys pattern.

2024-11-22 14:00 UTC, reisdev commented on .gitignore
> +**/*/swiftpm
`Package.resolved` is intended, mostly, for local use. Even the SPM repo ignores this file:

https://github.com/swiftlang/swift-package-manager/blob/main/.gitignore

2024-11-22 19:47 UTC, timea-v commented on Alfie/Alfie/Delegate/AppDelegate.swift
> +        if !serviceProvider.configurationService.isFeatureEnabled(.wishlist) {
Maybe we could have `var tabs` with all cases but `.wishlist` and just append `.wishlist` if it is enabled for better performance?

2024-11-22 19:52 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +        self.features = ConfigurationKey.allCases.map { configuration in
```suggestion
        features = ConfigurationKey.allCases.map { configuration in
```

2024-11-22 19:58 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +    private var store: Set<AnyCancellable> = []
Maybe it could be a single subscription?
```suggestion
    private var subscription: AnyCancellable?
```

2024-11-22 20:01 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +	@LocalizableResource<Self>(.title) static var title
Indentation is wrong

2024-11-22 20:02 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Localisation/LocalizableFeatureToggle.swift
> +		case title = "KeyFeatureToggle"
Indentation is wrong

2024-11-22 20:03 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +            let configuration: ConfigurationAppUpdateInfo = switch type {
Can you please explain why this change? The rule was disabled to follow Mindera style guide

2024-11-22 20:05 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/Providers/DebugConfigurationProvider.swift
> +    public func toggleAvailability() {
Missing new line

2024-11-22 20:05 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/Providers/DebugConfigurationProvider.swift
> +    // MARK: - ConfigurationProviderProtocol
Missing new line

2024-11-22 20:08 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/Providers/DebugConfigurationProvider.swift
> +        guard
Could you please use this style for `guard` with multiple conditions in this PR for consistency and to follow Mindera style guide?

2024-11-22 20:09 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/Providers/DebugConfigurationProvider.swift
> +        self.localConfig = config
```suggestion
        isReadySubject.value = UserDefaults.standard.bool(forKey: Self.debugConfigurationKey)
        localConfig = config
```

2024-11-22 20:09 UTC, timea-v commented on Alfie/Packages/Models/Sources/Features/FeatureToggleViewModelProtocol.swift
> +	func localizedName(for feature: String) -> LocalizedStringResource
Indentation is wrong

2024-11-22 20:10 UTC, timea-v commented on Alfie/Packages/Models/Sources/Services/Configuration/Providers/DebugConfigurationProviderProtocol.swift
> +import Combine
Is importing `Combine` needed?

2024-11-22 20:15 UTC, timea-v commented on Alfie/Alfie/Service/ServiceProvider.swift
> +		let providers: [ConfigurationProviderProtocol] = [localProvider]
I meant too many toggles, it could be a single picker for each feature (remote/on/off), but not so important.

2024-11-22 20:17 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/DebugMenuView.swift
> +                viewModel: FeatureToggleViewModel(
Line wrapping is not needed here.

2024-11-22 20:17 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/DebugMenuView.swift
> +                ContainerDemoViewModifier(
Maybe not needed to wrap lines here also

2024-11-22 20:19 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleViewModel.swift
> +    init(provider: some DebugConfigurationProviderProtocol) {
```suggestion
    init(provider: DebugConfigurationProviderProtocol) {
```

2024-11-24 07:03 UTC, naveenmindera commented on Alfie/Packages/Models/Sources/Features/FeatureToggleViewModelProtocol.swift
> +}
I see the feature toggle has heavier dependency on FeatureToggleViewModelProtocol. Consider breaking this into smaller protocols (ISP).

2024-11-24 07:20 UTC, naveenmindera commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleView.swift
> +                        get: { isEnabled },
Can we move this logic to viewModel to generate the bindings for each feature. A func that returns Binding<Bool> 

My idea is this can be as simple as 
ThemedToggleView(
                        isOn: viewModel.binding(for: feature)
                    )
thoughts?

2024-11-25 09:27 UTC, reisdev commented on Alfie/Alfie/Delegate/AppDelegate.swift
> +        if !serviceProvider.configurationService.isFeatureEnabled(.wishlist) {
That was one of my options, but this will imply on inserting the `.wishlist` at a specific position and that could lead to other problems if the items on the tab bar changes. Any way, it looks cleaner to insert if available rather then removing if it's not.

2024-11-25 09:46 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +            let configuration: ConfigurationAppUpdateInfo = switch type {
It was a syntax improvement, to use switch assignment instead of a closure. I reverted the rule enable/disable removal.

2024-11-25 09:48 UTC, reisdev commented on Alfie/Packages/Core/Sources/Services/Configuration/Providers/DebugConfigurationProvider.swift
> +        guard
Where can I find Mindera's style guide? I'm not used to it

2024-11-25 09:49 UTC, reisdev commented on Alfie/Packages/Models/Sources/Services/Configuration/Providers/DebugConfigurationProviderProtocol.swift
> +import Combine
Not anymore. Removed it.

2024-11-25 10:40 UTC, reisdev commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/FeatureToggleView.swift
> +                        get: { isEnabled },
Great catch. I did some improvements and made the VM responsible for this.

2024-11-25 10:42 UTC, reisdev commented on Alfie/Packages/Models/Sources/Features/FeatureToggleViewModelProtocol.swift
> +}
I was able to simplify this. Do you still see the need for multiple protocols?

2024-11-25 12:37 UTC, timea-v commented on Alfie/Alfie/Delegate/AppDelegate.swift
> +        var tabs: [TabScreen] = [.home(nil), .shop(tab: nil), .bag]
Home and shop cases have default values for parameters, you can skip adding them:
```suggestion
        var tabs: [TabScreen] = [.home(), .shop(), .bag]
```

2024-11-25 12:39 UTC, timea-v commented on Alfie/Packages/Core/Sources/Services/Configuration/ConfigurationService.swift
> +        guard let rawValue = providerValue(for: .appUpdate),
Please keep each condition on new line
```suggestion
        guard 
            let rawValue = providerValue(for: .appUpdate),
```

2024-11-25 14:29 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Extensions/ConfigurationKeyExtension.swift
> +
New line is not needed here:
"Add a newline between each case block in switch statements if at least one spans more than one line."

2024-11-25 14:37 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Extensions/ConfigurationKeyExtension.swift
> +        default:
Maybe it would be better to provide value for each case instead of using default, so that in the future if a new `ConfigurationKey` is added, a compiler error will force us to provide correct localization for that.

2024-11-25 18:12 UTC, timea-v commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Extensions/ConfigurationKeyExtension.swift
> +        default:
I meant to provide all the possible cases, here as I saw "case .custom(...):" is missing

2024-11-25 19:35 UTC, reisdev commented on Alfie/Alfie/Views/DebugMenu/FeatureToggle/Extensions/ConfigurationKeyExtension.swift
> +        default:
Sorry. Added the case

2024-11-26 12:58 UTC, p4checo requested changes
Still some pending bits here and there 😇

2024-11-26 13:13 UTC, reisdev commented
@p4checothe style guide doesn't state that I should only break the `guard` clause into multiple line if it exceeds 120. What rule should I follow?

https://github.com/Mindera/swift-style-guide?tab=readme-ov-file#golden-path

2024-11-26 13:15 UTC, p4checo commented
@reisdev You are correct. I've edited my comment and resolved the conversation 😉 

Our styleguide is long overdue a revision, but until that happens we should honor it. Thank you 🙏🏼

2024-11-26 13:19 UTC, naveenmindera approved these changes

2024-11-26 13:43 UTC, timea-v approved these changes

2024-11-26 15:06 UTC, p4checo requested changes

2024-11-26 15:06 UTC, p4checo commented on .gitignore
> +**/*/swiftpm
Maybe my explanation wasn't clear. We're **not supposed** to ignore the `.resolved` file inside the project, because Xcode uses it to store the project's / workspace's resolved dependencies 😅

2024-11-26 15:14 UTC, reisdev commented on .gitignore
> +**/*/swiftpm
Since it was already ignored, I assumed it should stay this way 😅. Now, I removed it.

2024-11-26 15:30 UTC, p4checo approved these changes

2024-11-26 15:51 UTC, merged